### ISSUE TITLE
PPM

### ISSUE THREAD

**Issue by FLYBYME** [RalfBrandt/Custom-MLP4DSM-Firmware#1]
Is there a way to put PPM out and not the DSM protocol?

**Comment by RalfBrandt** [comment]
Hi 
That functionality is not implemented jet, and I have no intention to implement that.
But you can change the code to archive the requested functionality.
Feel free, to fork, and create your own version of that project. 
Taking in account that the code memory is used by 95% jet you probably have to remove some other functionalities beside the generation of the serial DSM data stream.
Currently the output compare registers of all three timers are used (Timer 0 for LED , Timer 2 of the buzzer and timer 1 for ADC timing , systic and transmit timing.
 For a proper PPM signal you need a time’s output compare functionality. The dimming functionality of the LED (made by timer 0) is not really required, so you can remove this, and use timer 1 for the systic. This will free up the output compare register of timer 1. That can then be used to generate the PPM signal.
